name: CI Check Updates

on:
  schedule:
    - cron: "0 22 * * *" # Daily at 05:00 (UTC+7)
  push:
    branches:
      - main
    paths:
      - 'config.toml'
  workflow_dispatch:

jobs:
  check:
    name: Check New Patches
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    outputs:
      should_build: ${{ steps.check_step.outputs.SHOULD_BUILD }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Checkout Previous Release Notes
        run: |
          git checkout origin/releaselog release.md || true

      - name: Check for Updates
        id: check_step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "push" ] || [ ! -f "release.md" ]; then
            echo "SHOULD_BUILD=1" >> "$GITHUB_OUTPUT"
          else
            OUTPUT=$(python build.py --check-updates)
            echo "$OUTPUT"
            if echo "$OUTPUT" | grep -q "SHOULD_BUILD=1"; then
              echo "SHOULD_BUILD=1" >> "$GITHUB_OUTPUT"
            else
              echo "SHOULD_BUILD=0" >> "$GITHUB_OUTPUT"
            fi
          fi

      - name: Clean Old Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L 100 --json databaseId -q '.[].databaseId' | tail -n +15 | xargs -I ID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || true

  build:
    name: Trigger Build
    needs: check
    if: needs.check.outputs.should_build == '1'
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
